def generate_reasoning(candidate, sub_scores):
    """
    Generates a deterministic XAI reasoning string that mimics an expert AI recruiter.
    It breaks down the fit into Semantic Skills, Career Trajectory, Behavioral Intent,
    and Education.
    """
    profile = candidate.get('profile', {})
    yoe = profile.get('years_of_experience', 0)

    # Extract sub-scores generated by scorer.py
    matched_clusters = sub_scores.get('matched_clusters', [])
    velocity = sub_scores.get('velocity', {})
    beh_status = sub_scores.get('beh_status', 'Active')

    # 1. Semantic Match Statement
    if len(matched_clusters) >= 4:
        sem_str = f"Exceptional technical fit, covering {len(matched_clusters)}/5 core semantic clusters."
    elif len(matched_clusters) >= 2:
        sem_str = f"Strong semantic overlap in key areas including {', '.join(matched_clusters[:2]).replace('_', ' ')}."
    else:
        sem_str = "Partial technical alignment."

    # 2. Career Trajectory Statement
    traj_parts = []

    if velocity.get('highest_level', 0) >= 3 and yoe <= 5 and yoe > 0:
        traj_parts.append(f"Demonstrates high promotion velocity (reached Senior+ in {yoe} years).")
    else:
        traj_parts.append(f"{yoe} years of steady progression.")

    if velocity.get('has_tier_1'):
        traj_parts.append("Background includes Tier-1 product companies.")
    if velocity.get('all_consulting'):
        traj_parts.append("Background is entirely consulting-based.")
    if velocity.get('has_large_company') and not velocity.get('has_tier_1'):
        traj_parts.append("Experience at large-scale engineering organizations.")

    edu_bonus = velocity.get('education_bonus', 0)
    if edu_bonus >= 10:
        traj_parts.append("Tier-1 academic background in a relevant discipline.")
    elif edu_bonus >= 5:
        traj_parts.append("Strong academic foundation from a reputable institution.")

    traj_str = " ".join(traj_parts)

    # 3. Behavioral / Intent Statement
    signals = candidate.get('redrob_signals', {})
    rr = signals.get('recruiter_response_rate', 0.5)
    rr_str = f"high ({rr:.2f})" if rr >= 0.7 else (f"moderate ({rr:.2f})" if rr >= 0.4 else f"low ({rr:.2f})")

    intent_parts = []

    if signals.get('open_to_work_flag'):
        intent_parts.append(f"open to work with a {rr_str} response rate")
    else:
        intent_parts.append(f"passive candidate with a {rr_str} response rate")

    notice = signals.get('notice_period_days', -1)
    if notice != -1 and notice <= 30:
        intent_parts.append(f"available within {notice} days")
    elif notice > 90:
        intent_parts.append(f"notice period of {notice} days")

    saved = signals.get('saved_by_recruiters_30d', 0)
    if saved >= 3:
        intent_parts.append(f"saved by {saved} recruiters in the last 30 days")

    icr = signals.get('interview_completion_rate', -1)
    if icr != -1 and icr < 0.5:
        intent_parts.append("low interview completion rate (risk flag)")

    oar = signals.get('offer_acceptance_rate', -1)
    if oar != -1 and oar < 0.3:
        intent_parts.append("historically low offer acceptance rate")

    beh_str = "High engagement intent: " + ", ".join(intent_parts) + "." if intent_parts else "Engagement signals unavailable."

    if beh_status == "Stale":
        beh_str += " Note: Profile activity indicates stale engagement."

    # Combine into a professional XAI justification
    reasoning = f"[AI Rationale] {sem_str} {traj_str} {beh_str}"
    return reasoning
