def generate_reasoning(candidate, sub_scores):
    """
    Generates a deterministic XAI reasoning string that mimics an expert AI recruiter.
    It breaks down the fit into Semantic Skills, Career Trajectory, and Behavioral Intent.
    """
    profile = candidate.get('profile', {})
    yoe = profile.get('years_of_experience', 0)
    title = profile.get('current_title', 'Engineer')
    
    # Extract sub-scores generated by scorer.py
    matched_clusters = sub_scores.get('matched_clusters', [])
    velocity = sub_scores.get('velocity', {})
    beh_status = sub_scores.get('beh_status', 'Active')
    
    # 1. Semantic Match Statement
    if len(matched_clusters) >= 4:
        sem_str = f"Exceptional technical fit, covering {len(matched_clusters)}/5 core semantic clusters."
    elif len(matched_clusters) >= 2:
        sem_str = f"Strong semantic overlap in key areas including {', '.join(matched_clusters[:2]).replace('_', ' ')}."
    else:
        sem_str = "Partial technical alignment."
        
    # 2. Career Trajectory Statement
    traj_parts = []
    
    if velocity.get('highest_level', 0) >= 3 and yoe <= 5 and yoe > 0:
        traj_parts.append(f"Demonstrates high promotion velocity (reached Senior+ in {yoe} years).")
    else:
        traj_parts.append(f"{yoe} years of steady progression.")
        
    if velocity.get('has_tier_1'):
        traj_parts.append("Background includes Tier-1 product companies.")
    if velocity.get('all_consulting'):
        traj_parts.append("Background is entirely consulting-based.")
        
    traj_str = " ".join(traj_parts)
    
    # 3. Behavioral / Intent Statement
    signals = candidate.get('redrob_signals', {})
    rr = signals.get('recruiter_response_rate', 0.5)
    rr_str = f"high ({rr:.2f})" if rr >= 0.7 else (f"moderate ({rr:.2f})" if rr >= 0.4 else f"low ({rr:.2f})")
    
    if signals.get('open_to_work_flag'):
        beh_str = f"High engagement intent: open to work with a {rr_str} response rate."
    else:
        beh_str = f"Passive candidate with a {rr_str} response rate."
        
    if beh_status == "Stale":
        beh_str += " Note: Profile activity indicates stale engagement."

    # Combine into a professional XAI justification
    reasoning = f"【AI Rationale】 {sem_str} {traj_str} {beh_str}"
    return reasoning
